services:
  db:
    image: mysql:8.0
    container_name: otaku_mysql
    environment:
      MYSQL_DATABASE: otakushop
      MYSQL_USER: otaku
      MYSQL_PASSWORD: otaku_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"   # tránh đụng 3306 trên Windows
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password","--mysqlx=0"]
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-uroot","-proot_pass"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DATABASE_URL: "mysql://otaku:otaku_pass@db:3306/otakushop"
      SEED: "1"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh","-c","./docker-entrypoint.sh npm run dev"]

volumes:
  db_data:
